version: "3"

services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - /etc/ssl/nginx:/etc/ssl/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - bc30138-net

networks:
  bc30138-net:
    name: bc30138-net
    driver: bridge